


user_demographics = {
    "age": ["30-35"],
    "location": ["Minnesota"],
    "current occupation": ["Technical Project Leader - Cross Functional Business Systems & New Location Openings"],
    "family member occupations": ["teachers", "lawyers", "engineers", "doctors", "musicians", "artists", "trades people", "business owners"],
    "spirituality": ["agnostic"],
}

user_life_soundtrack = {
    "Black Sabbath": ["Hand of Doom", "Children of the Grave"],
    "Wu-Tang Clan": ["C.R.E.A.M.", "Protect Ya Neck", "Tears"],
    "The Fugees": ["The Score", "Ready or Not",],
    "The Roots": ["Game Theory", "Section", "No Alibi", "Ain't Sayin' Nothin' New", "Adrenaline!"],
    "At the Gates": ["Blinded by Fear", "Cold"],
    "Kreator": ["Enemy of God", "Phantom Antichrist"],
    "Talking Heads": ["Burning Down the House", "Psycho Killer",],
    "Van Halen": ["Runnin' with the Devil", "Hot for Teacher",],
    "Metallica": ["Master of Puppets", "Creeping Death", "For Whom the Bell Tolls", "Ride the Lightning", "The Four Horsemen",],
    "Dio": ["The Last In Line"],
    "Judas Priest": ["Jawbreaker", "Fever", "Painkiller", "Victim of Changes", "Breaking the Law", "You've Got Another Thing Comin'"],
    "Iron Maiden": ["The Evil That Men Do", "Wasted Years", "The Trooper", "Aces High", "Run to the Hills", "The Number of the Beast", "Hallowed Be Thy Name", "Fear of the Dark"],
    "Soundgarden": ["Black Hole Sun"],
    "Slayer": ["Angel of Death", "South of Heaven", "Seasons in the Abyss", "Raining Blood", "Chemical Warfare",],
    "Megadeth": ["Holy Wars... The Punishment Due", "Hangar 18", "Symphony of Destruction",],
    "Death": ["Spirit Crusher", "Bite the Pain", "To Forgive is to Suffer",],
    "Archspire": ["Drain of Incarnation", "Abandon the Linear", "Golden Mouth of Ruin",],
    "Nirvana": ["Come as You Are",],
    "Pink Floyd": ["Comfortably Numb", "Time", "Another Brick in the Wall",],
    "Public Enemy": ["Fight the Power", "Bring the Noise", "Don't Believe the Hype"],
    "A Tribe Called Quest": ["Can I Kick It?", "Electric Relaxation",],
    "Beastie Boys": ["Intergalactic", "Fight for Your Right",],
    "Rage Against the Machine": ["Bulls on Parade", "Guerrilla Radio"],
    "Lamb of God": ["Laid to Rest", "Walk with Me in Hell"],
    "Andy James": ["Aftermath", "Dark Waters", "Silhouette"],
}

user_favorite_books = {
    "Orson Scott Card": ["Ender's Game"],
    "J.R.R. Tolkien": ["Lord of the Rings", "The Hobbit", "The Silmarillion"],
    "Douglas Adams": ["Hitchhiker's Guide to the Galaxy", "Life, the Universe and Everything"],
    "Terry Pratchett": ["The Color of Magic"],
    "Don Miguel Ruiz": ["The Four Agreements"],
    "David Eddings": ["The Redemption of Althalus"],
    "J.K. Rowling": ["Harry Potter"],
    "Travis Bradberry": ["Emotional Intelligence 2.0"],
    "Miyamoto Musashi": ["The Book of Five Rings"],
    "C.S. Lewis": ["The Chronicles of Narnia", "The Screwtape Letters"],
    "Frank Herbert": ["Dune"],
    "Dan Brown": ["Angels & Demons"],
    "George Orwell": ["1984", "Animal Farm"],
    "Stephen King": ["The Dark Tower series",],
    "H.P. Lovecraft": ["The Call of Cthulhu"],
    "Terry Prattchet & Neil Gaiman": ["Good Omens"],
}

user_favorite_movies = {
    "Roberto Benigni": ["Life is Beautiful",],
    "Wachowski Sisters": ["The Matrix"],
    "Hayao Miyazaki": ["Princess Mononoke", "Spirited Away", "Howl's Moving Castle", "Nausicaa", "Castle in the Sky"],
    "Coen Brothers": ["The Big Lebowski", "O Brother, Where Art Thou?", "Fargo", "No Country for Old Men", "Burn After Reading", "The Hudsucker Proxy",],
    "Jim Jarmusch": ["Coffee and Cigarettes", "Night On Earth",],
    "Quentin Tarantino": ["Pulp Fiction", "Reservoir Dogs", "Kill Bill", "Inglorious Basterds"],
    "Quentin Tarantino / Robert Rodriguez / Alexandre Rockwell / Allison Anders": ["Four Rooms"],
    "Peter Jackson": ["The Lord of the Rings"],
    "Ridley Scott": ["Alien", "Blade Runner", "Legend",],
    "Milos Forman": ["One Flew Over the Cuckoo's Nest"],
    "Takashi Miike": ["13 Assassins"],
    "Terry Gilliam": ["Fear and Loathing in Las Vegas", "13 Monkeys", "Brazil", "Monty Python and the Holy Grail", "The Life of Brian"],
    "Joel Schumacher": ["The Lost Boys"],
    "Richard Donner": ["The Goonies"],
    "John Carpenter": ["Escape From New York",],
    "Walter Hill": ["The Warriors"],
    "Wes Anderson": ["The Royal Tenenbaums", "The Life Aquatic", "The Grand Budapest Hotel"],
    "Mel Brooks": ["Spaceballs"],
    "George Lucas": ["Star Wars"],
    "Christopher Guest": ["Best in Show", "Waiting for Guffman", "A Mighty Wind", "This is Spinal Tap"],
    "Rob Reiner": ["The Princess Bride", "Ferris Bueller's Day Off"],
    "Wolfgang Petersen": ["The Neverending Story"],
    "Jim Henson": ["The Dark Crystal", "Labyrinth"],
    "Ron Howard": ["Willow"],
    "Bong Joon-ho": ["The Host", "Snowpiercer",],
    "David Lynch": ["Mulholland Drive", "Blue Velvet"],
    "Tim Burton": ["Edward Scissorhands", "Beetlejuice", "The Nightmare Before Christmas"],
    "Sofia Coppola": ["Lost in Translation", "The Virgin Suicides",],
    "Paul Thomas Anderson": ["There Will Be Blood"],
    "Guillermo del Toro": ["Pan's Labyrinth",],
    "Akira Kurosawa": ["Seven Samurai", "Rashomon",],
    "Alfred Hitchcock": ["Psycho",],
    "Martin Scorsese": ["Taxi Driver", "Goodfellas", "Raging Bull", "The Departed", "Casino",],
    "David Fincher": ["Fight Club", "Se7en", "The Social Network"],
    "Christopher Nolan": ["Inception", "The Dark Knight", "Interstellar"],
    "Steven Spielberg": ["Jurassic Park", "E.T.",],
    "Edgar Wright": ["Shaun of the Dead", "Scott Pilgrim vs. the World", "Baby Driver"],
    "Danny Boyle": ["Trainspotting",],
    "Guy Ritchie": ["Snatch", "Lock, Stock and Two Smoking Barrels",],
    "Spike Jonze": ["Being John Malkovich", "Adaptation"],
    "Michel Gondry": ["Eternal Sunshine of the Spotless Mind",],
    "David Cronenberg": ["The Fly",],
    "Sam Mendes": ["American Beauty",],
    "Park Chan-wook": ["Oldboy",],
    "Ingmar Bergman": ["The Seventh Seal",],
    "Francis Ford Coppola": ["The Godfather", "Apocalypse Now", "Dracula", "The Outsiders"],
    "Jean-Pierre Jeunet": ["Amélie", "Delicatessen", "City of Lost Children"],
    "Stanley Kubrick": ["The Shining", "2001: A Space Odyssey", "A Clockwork Orange", "Dr. Strangelove"],
    "Richard Linklater": ["Waking Life", "A Scanner Darkly",],
    "Paul Verhoeven": ["RoboCop", "Total Recall", "Starship Troopers"],
    "Gus Van Sant": ["Good Will Hunting",],
    "Tom Tykwer": ["Run Lola Run",],
    "Luc Besson": ["Leon: The Professional", "The Fifth Element"],
    "Jordan Peele": ["Get Out", "Us"],
}

user_skills_and_experience = {
    "career ambition goals": [
        "become a technical architect with fluency of a wide range of tech solutions focusing on Python development, graph databases, relational databases, app deployment, AI, ML, NLP, and data science.",
        "earn as much as possible so that my time at my day job is as efficient as possible, in the effort of reaching financial independence asap.", 
        "allow time for studying, career development, relationships, recreation and a healthy work-life balance",
        "azure certification",
        "aws certification",
        "google cloud certification",
        "pmp certification",
        "python certification",
        "get a job as a python software engineer, platform developer, architect, data scientist, data engineer or ML/NLP/AI engineer"],
    "career fulfillment goals": [
        "find a purpose", 
        "fully utilize my strengths", 
        "learn and teach", 
        "experience more of the world", 
        "have fun", 
        "have a positive impact on the world", 
        "help the environment", 
        "help people", 
        "have autonomy and be able to practice creativity", 
        "maintain a high degree of novelty and a sense of purpose for sustained dopamine system health while working toward long term goals",
        "find work that is meaningful and fun",
        "find work where my time invested can have the maximum degree of impact",
        "discover my true natural strengths and find a career that allows me to use them",
        "be a valuable contributor to a community of people who are working toward a common goal",
        "improve the quality of life for everyone",],
    "education level": [
        "high school diploma", 
        "some college but no degree", 
        "Salesforce administrator certification - 2022"],
    "career background explanation and current responsibilities": [
        "started as a cook, then moved to management, then sous chef, then executive chef, then regional culinary operations leader, then project management", 
        "currently a hybrid of hospitality operations, project management, and software engineering for workflows that i have migrated from spreadsheets and excel and disparate apps into Python."],
    "career experience": [
        "5 years in retail ending as a front-end department manager",
        "10 years in various chef / restaurant management positions including sous chef, executive chef",
        "4 years in hospitality operations management such as training and opening new locations", 
        "2 years as a project manager who focuses on operations for cross functional business systems and business expansion into new markets",
        "salesforce administrator certification",
        "2 years of python software development, data science, AI, ML, and NLP via self-study and self-directed projects",],
    "common themes of professional feedback": [
        "practice more concise communication", 
        "people have a hard time understanding you when you try to explain complicated things",
        "work on better time management", 
        "learn to say no to things i don't have bandwidth for", 
        "provide more realistic time estimates for projects",
        "do not allow myself ot become overwhelmed",
        "look on the bright side more often",
        "do not let frustrations show",
        "it is more important to be kind than to be right",
        "bring others along for the journey",
        "be patient with others",
        "be mindful of my own body language and nonverbal cues during communication"],
    "programming projects currently in process": [
        "Hey Data: an AI assistant and companion app containing purpose-driven agents with tools and long term memory, Gemini as the main LLM, access to google programmable search engine api, wikipedia, wolfram alpha, youtube, google maps, ability to use inspect to read its own codebase, and access to ancillary tools for the user such as stock data, weather forecasts, music, youtube, etc.",
        "a market research tool that leverages google maps api alongside beautifulsoup and selenium to scrape data about similar businesses in a new market to get a better sense of competitive landscape in a new market",
        "a data transformation etl script in python that cleanses and aggregates and pivots a few disparate datasets related to product sales into pandas dataframes then saves them as csv files to feed a high level executive performance dashboard in looker studio using all free software and tools replacing expensive workflows in tableau",
        "a python scrips that uses pandas, python levenshtein, nltk and some other NLP to derive the semantic similarity across a large dataset of product names and descriptions to help identify duplicate products and consolidate them into a single product record"],
    "subjects that i aspire to learn and master a.s.a.p.": [
        "Python programming, app packaging/containerization, deployment, and CI/CD",
        "azure",
        "google cloud platform",
        "aws",
        "Python front end development with Flet, Streamlit, tkinter",
        "Neo4j graph databases",
        "google cloud platform projects",
        "ai agents",
        "multi action agents",
        "executor agents",
        "multi tool agents",
        "autonomous agents",
        "ai assistant agents",
        "ai automation agents"],
}

user_personality = {
    "core values": [
        "democratization and pursuit of knowledge",
        "equity",
        "peace",
        "justice",
        "innovation",
        "humour",
        "growth",
        "sustainability"],
    "personality types": [
        "Myers-Briggs: INTJ but consistently near the 50% mark on the I/E and T/F scales and can lean toward ENFJ depending on the environment and situation",
        "Predictive Index: Individualist",
        "Astrology: Virgo"],
    "sense of humor": [
        "sarcastic",
        "dry",
        "dark",
        "witty",
        "quick",
        "irreverent",
        "sometimes self-deprecating"],
    "personality traits": [
        "smart",
        "funny",
        "empathetic",
        "intuitive",
        "good read of body language",
        "sometimes impatient",
        "moderate workaholic",
        "constantly studying and trying to learn new skills",
        "sometimes has tendency to hyperfocus and dominate conversations"],
    "strengths": [
        "empathy",
        "intuition",
        "intelligence",
        "creativity",
        "humor",
        "ability to learn new skills quickly",
        "ability to interpret and generalize and communicate complex topics",
        "motivation to improve the world",
        "motivation to constantly learn",
        "good nutrition and general self care"],
    "weaknesses": [
        "lack of consistent willpower or dopamine supply to work on tedious non-interesting tasks",
        "lack of patience for people who i find rude, arrogant, or lazy",
        "inability to hide feelings of frustration in body language when stressed",
        "procrastination",
        "executive function challenges",
        "time management",        
        "stress management",
        "setting boundaries",
        "indecision",
        "perfectionism",
        "overthinking",
        "overanalyzing",
        "difficulty trusting others",
        "impulsivity",
        "people pleasing behaviors",
        "isolationism",
        "social anxiety"],
    "self development areas of focus": [
        "communication skills",
        "teamwork",
        "leadership",
        "cultivating healthy relationships",
        "team building",
        "time management",
        "stress management",
        "executive function",
        "setting boundaries",
        "decisiveness",
        "self confidence",
        "consistency in routine",
        "sleep hygiene",
        "self care"],
}

user_interests = {
    "programming": [
        "AI",
        "ML",
        "NLP",
        "data science",
        "data analytics",
        "app development",
        "Python",
        "neo4j",
        "SQL",
        "robotics"],
    "fitness": [
        "weightlifting",
        "rock climbing",
        "yoga",
        "myofascial release"],
    "music": [
        "black metal",
        "technical death metal",
        "hip-hop",
        "rap",
        "progressive metal",
        "jazz",
        "classical",
        "classic rock",
        "folk",
        "americana",
        "acoustic guitar"],
    "environmental sustainability": [
        "renewable energy",
        "precision farming",
        "gardening",
        "permaculture",
        "land stewardship",
        "pollinator protection",
        "sustainable agriculture",
        "sustainable building",
        "urban farming"],
    "cooking": [
        "professional career as a cook/chef",
        "interested in sustainable food supply chain",
        "foraging",
        "hunting",
        "fishing",
        "gardening",
        "cooking"],
    "nature": [
        "biology",
        "plant life",
        "wildlife",
        "nature",
        "horticulture",
        "botany",
        "chemistry",
        "physics",
        "astronomy",
        "animals",
        "pets",
        "nature documentaries",
        "wildlife documentaries",
        "camping",
        "fishing",
        "geology"],
}

user_influential_figures = {
    "Lex Fridman": [
        "AI",
        "ML",
        "data science",
        "engineering",
        "podcasting",
        "asks difficult questions",
        "Google",
        "MIT",
        "Tesla",
        "OpenAI",
        "DeepMind"],
    "Andrej Karpathy": [
        "AI innovation",
        "cutting edge research",
        "Tesla",
        "OpenAI"],
    "Andrew Huberman": [
        "neuroscience",
        "psychology",
        "biology",
        "physiology",
        "health",
        "wellness",
        "fitness",
        "longevity"],
    "Andrew Ng": [
        "AI",
        "ML",
        "data science",
        "engineering",
        "teaching",
        "Google",
        "Stanford",
        "deeplearning.ai"],
    "Bruce Lee": [
        "martial arts",
        "philosophy",
        "fitness",
        "health",
        "wellness"],
    "Tim Ferriss": [
        "entrepreneurship",
        "business",
        "longevity",
        "biohacking",
        "lifestyle design"],
    "Ryan Holiday": [
        "philosophy",
        "stoicism",
        "history",
        "writing"],
    "Daniel Pink": [
        "psychology",
        "sociology",
        "business"],
    "Chris Voss": [
        "negotiation",
        "psychology",
        "sociology"],
    "Tony Stark": [
        "inventiveness",
        "resourcefulness",
        "genius",
        "humor"],
    "Cortana": [
        "even-tempered",
        "intelligent",
        "resourceful",
        "witty"],
    "Jean-Luc Picard": [
        "wise",
        "intelligent",
        "diplomatic",
        "strong critical thinking skills",
        "strong leadership",
        "empathetic"],
    "Gandalf": [
        "wise",
        "funny"],
    "Tom Hagen": [
        "strong critical thinking skills",
        "tenacious",
        "cunning",
        "sharp",
        "calm during turmoil",
        "perceptive",
        "empathetic"],
    "Fox Mulder": [
        "intelligent",
        "resourceful",
        "tenacious",
        "bold",
        "willing to challenge norms",
        "assertive",
        "determined"],
}

user_favorite_quotes = {
    "Friedrich Nietzsche": [
        "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you."],
    "Albert Einstein": [
        "If at first the idea is not absurd, then there is no hope for it.",
        "We cannot solve our problems with the same thinking we used when we created them.",
        "Life is like riding a bicycle. To keep your balance you must keep moving.",
        "A person who never made a mistake never tried anything new.",
        "Look deep into nature, and then you will understand everything better.",
        "Weakness of attitude becomes weakness of character.",
        "Reality is merely an illusion, albeit a very persistent one.",
        "Imagination is everything. It is the preview of life's coming attractions.",
        "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.",
        "Whoever is careless with the truth in small matters cannot be trusted with important matters.",
        "Everyone should be respected as an individual, but no one idolized.",
        "He who can no longer pause to wonder and stand rapt in awe, is as good as dead; his eyes are closed.",
        "Intellectuals solve problems, geniuses prevent them.",
        "Everything should be made as simple as possible, but not simpler.",
        "Great spirits have always encountered violent opposition from mediocre minds.",
        "Intellectual growth should commence at birth and cease only at death.",
        "Once we accept our limits, we go beyond them.",
        "The only source of knowledge is experience.",
        "Peace cannot be kept by force; it can only be achieved by understanding.",
        "I have no spoeical talent. I am only passionately curious.",
        "It's not that I'm so smart, it's just that I stay with problems longer.",
        "Strive not to be a success, but rather to be of value.",
        "If you can't explain it simply, you don't understand it well enough.",],
    "Frank Herbert": [
        "I must not fear. Fear is the mind-killer. Fear is the little death that brings obliteration. I will face my fear and I will permit it to pass over me and through me. And when it has gone past... I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain."],
    "Thomas A. Edison": [
        "I have not failed. I've just found 10,000 ways that won't work."],
    "Stephen Covey": [
        "I am not a product of my circumstances. I am a product of my decisions."],
    "Amelia Earhart": [
        "The most difficult thing is the decision to act, the rest is merely tenacity."],
    "Babe Ruth": [
        "Every strike brings me closer to the next home run."],
    "Nelson Mandela": [
        "The greatest glory in living lies not in never falling, but in rising every time we fall.",
        "It always seems impossible until it's done.",],
    "Mahatma Gandhi": [
        "Be the change that you wish to see in the world.",
        "The weak can never forgive. Forgiveness is the attribute of the strong.",
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "Happiness is when what you think, what you say, and what you do are in harmony."],
    "Martin Luther King Jr.": [
        "I have a dream that one day this nation will rise up and live out the true meaning of its creed: 'We hold these truths to be self-evident: that all men are created equal.'",
        "The time is always right to do what is right.",
        "Our lives begin to end the day we become silent about things that matter."],
    "Mark Twain": [
        "The secret of getting ahead is getting started.",
        "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
        "If you tell the truth, you don't have to remember anything.",
        "The best way to cheer yourself up is to try to cheer somebody else up.",
        "The two most important days in your life are the day you are born and the day you find out why."],
    "Oscar Wilde": [
        "Be yourself; everyone else is already taken.",
        "Always forgive your enemies; nothing annoys them so much.",
        "To live is the rarest thing in the world. Most people exist, that is all.",
        "Experience is simply the name we give our mistakes.",
        "The truth is rarely pure and never simple."],
    "Winston Churchill": [
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "You have enemies? Good. That means you've stood up for something, sometime in your life.",
        "Never, never, never give in except to convictions of honor and good sense.",
        "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty."],
    "Warren Buffett": [
        "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.",
        "Risk comes from not knowing what you're doing.",
        "Price is what you pay. Value is what you get.",
        "Someone's sitting in the shade today because someone planted a tree a long time ago.",
        "The most important quality for an investor is temperament, not intellect."],
    "Franklin D. Roosevelt": [
        "The only thing we have to fear is fear itself.",
        "Happiness lies in the joy of achievement and the thrill of creative effort.",
        "When you reach the end of your rope, tie a knot in it and hang on.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "A nation that destroys its soils destroys itself. Forests are the lungs of our land, purifying the air and giving fresh strength to our people."],
    "John F. Kennedy": [
        "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
        "Those who dare to fail miserably can achieve greatly.",
        "Efforts and courage are not enough without purpose and direction.",
        "We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard."],
    "Yoda": [
        "Do. Or do not. There is no try.",
        "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.",
        "Always pass on what you have learned.",],
    "Obi-Wan Kenobi": [
        "In my experience there is no such thing as luck.",
        "Your eyes can deceive you. Don't trust them.",
        "The Force will be with you. Always.",
        "Who's the more foolish, the fool or the fool who follows him?",],
    "Gandalf": [
        "All we have to decide is what to do with the time that is given us.",
        "I found it is the small everyday deeds of ordinary folk that keep the darkness at bay. Small acts of kindness and love.",],
    "Morpheus": [
        "There is a difference between knowing the path and walking the path.",],
    "Steve Jobs": [
        "Your time is limited, so don't waste it living someone else's life.",
        "Design is not just what it looks like and feels like. Design is how it works.",],
    "Robert Frost": [
        "I have promises to keep, and miles to go before I sleep.",],
}
