


user_demographics = {
    "age": ["30-35"],
    "location": ["Minnesota"],
    "current occupation": ["Technical Project Leader - Cross Functional Business Systems & New Location Openings"],
    "family and role model occupations": ["teachers", "lawyers", "engineers", "doctors", "musicians", "artists", "trades people", "business owners"],
}

user_life_soundtrack = {
    "Black Sabbath": ["Hand of Doom", "Wicked World", "Children of the Grave"],
    "Talking Heads": ["Burning Down the House"],
    "Van Halen": ["Runnin' with the Devil"],
    "Metallica": ["Master of Puppets"],
    "Dio": ["The Last In Line"],
    "Judas Priest": ["Jawbreaker", "Fever", "Painkiller", "Victim of Changes", "Breaking the Law", "You've Got Another Thing Coming"],
    "Iron Maiden": ["The Evil That Men Do", "Wasted Years", "The Trooper"],
}

user_favorite_books = {
    "Orson Scott Card": ["Ender's Game"],
    "J.R.R. Tolkien": ["Lord of the Rings"],
    "Douglas Adams": ["Hitchhiker's Guide to the Galaxy"],
    "Terry Pratchett": ["The Color of Magic"],
    "Don Miguel Ruiz": ["The Four Agreements"],
    "David Eddings": ["The Redemption of Althalus"],
    "J.K. Rowling": ["Harry Potter"],
    "Travis Bradberry": ["Emotional Intelligence 2.0"],
    "Miyamoto Musashi": ["The Book of Five Rings"],
}

user_favorite_movies = {
    "Wachowski Sisters": ["The Matrix"],
    "Coen Brothers": ["The Big Lebowski", "O Brother, Where Art Thou?"],
    "Jim Jarmusch": ["Coffee and Cigarettes", "A Night On Earth"],
    "Quentin Tarantino / Robert Rodriguez / Alexandre Rockwell / Allison Anders": ["Four Rooms"],
    "Peter Jackson": ["The Lord of the Rings"],
    "Ridley Scott": ["Alien"],
    "Milos Forman": ["One Flew Over the Cuckoo's Nest"],
    "Stanley Kubrick": ["The Shining"],
    "Takashi Miike": ["13 Assassins"],
    "Terry Gilliam": ["13 Monkeys", "Brazil", "Monty Python and the Holy Grail"],
    "Joel Schumacher": ["The Lost Boys"],
    "Richard Donner": ["The Goonies"],
    "John Carpenter": ["Escape From New York"],
    "Walter Hill": ["The Warriors"],
    "Mel Brooks": ["Spaceballs"],
    "George Lucas": ["Star Wars"],
    "Christopher Guest": ["Best in Show", "Waiting for Guffman", "A Mighty Wind"],
}

user_skills_and_experience = {
    "career ambition goals": ["become a technical platform architect who is competent with full-stack and has fluency of a wide range of tech products and solutions but focuses primarily on Python server side development, neo4j graph databases, SQL relational databases, app development, AI, ML, NLP, and data science."],
    "career fulfillment goals": ["find a career path that is fulfilling, contributes to the greater good, and allows me to fully use my strengths, pushes me to learn, allows me to teach, lets me see and experience more of the world, and is fun"],
    "career purpose goals": ["build a career that is purposeful, meaningful, has a positive impact on the world, helps the environment, helps people, allows for autonomy and creativity, is fun, and has a high degree of novelty and purpose to sustain long term dopamine reward synergy for the user and their reward approach to work"],
    "education level": ["no college degree","high school graduate","some college, no degree","Salesforce certified administrator"],
    "career background": ["started in restaurants as a cook, then moved to management as a chef, then moved to project management, then moved to a hybrid of operations, project management, and self-directed software engineering for ad-hoc jobs that i learned how to do in python - i currently do all 3 while also managing implementations such as helping roll out new inventory or point of sale systems, etc., and also help oversee new location openings for a large scale retail and hospitality business"],
    "career experience": [
        "5 years in retail ending as a front-end department manager",
        "10 years in various chef / restaurant management positions including sous chef, executive chef",
        "2 years in hospitality operations management such as training and opening new locations", 
        "2 years as a project manager who focuses on operations for cross functional business systems and business expansion into new markets"],
    "common themes of professional feedback": [
        "practice more concise communication", 
        "work on better time management", 
        "learn to say no to things i don't have bandwidth for", 
        "provide more realistic time estimates for projects",
        "do not allow myself ot become overwhelmed",
        "look on the bright side more often",
        "do not let frustrations show",
        "it is more important to be kind than to be right",
        "bring others along for the journey",
        "be patient with others",
        "be mindful of my own body language and nonverbal cues during communication"],
    "tech industry experience": [
        "salesforce administrator certification",
        "1 year of python software engineering self-study",
        "1 year of python data science self-study",
        "1 year of AI, ML, and NLP self-study"],
    "programming projects currently in process": [
        "Hey Data: an AI assistant and companion app that centers around a number of purpose-driven agents with tools, reasoning, and long term memory including Gemini as the main LLM, access to google programmable search engine api, wikipedia, wolfram alpha, youtube, google maps, the ability to use the inspect package to read its own codebase, and access to ancillary tools for the user such as stock data, weather forecasts, music, youtube, etc.",
        "a market research tool that leverages google maps api alongside beautifulsoup and selenium to scrape data about similar businesses in a new market to get a better sense of competitive landscape in a new market",
        "a data transformation etl script in python that cleanses and aggregates and pivots a few disparate datasets related to product sales into pandas dataframes then saves them as csv files to feed a high level executive performance dashboard in looker studio using all free software and tools replacing expensive workflows in tableau",
        "a python scrips that uses pandas, python levenshtein, nltk and some other NLP to derive the semantic similarity across a large dataset of product names and descriptions to help identify duplicate products and consolidate them into a single product record"],
    "jubjects that i aspire to learn and master": [
        "Python programming",
        "python app packaging",
        "python app containerization",
        "python app deployment",
        "python model deployment",
        "CI/CD",
        "azure",
        "google cloud platform",
        "aws",
        "AI",
        "ML",
        "NLP",
        "data engineering",
        "Python app development",
        "Python front end development with Flet, Streamlit",
        "Neo4j graph databases",
        "google cloud projects",
        "langchain",
        "openai",
        "google generative ai",
        "ai agents",
        "multi action agents",
        "executor agents",
        "multi tool agents",
        "autonomous agents",
        "ai assistant agents",
        "ai companion agents",
        "ai research assistant agents",
        "ai automation agents",
        "ai time management assistant agents",
        "strong/static/dynamic/weak typing",
        "learning more programming languages",
        "becoming language agnostic"],
    "tangible medium-term career goals": [
        "azure certification",
        "aws certification",
        "google cloud certification",
        "pmp certification",
        "python certification",
        "get a job as a python software engineer"],
    "conceptual career goals": [
        "find work that is meaningful and that is fun for me",
        "find work where my time invested can have the maximum degree of impact so that i simultaneously fulfill my need for creativity and purpose and also have time for relationships and personal development and recreation and a healthy work-life balance",
        "discover my true natural strengths and find a career that allows me to use them",
        "be a valuable contributor to a strong community of people who are working toward a common goal",
        "improve the world",
        "improve the quality of life for everyone",
    ],
}

user_personality = {
    "core values": [
        "democratization and pursuit of knowledge",
        "equity",
        "peace",
        "justice",
        "innovation",
        "humour",
        "growth",
        "sustainability"],
    "personality types": [
        "Myers-Briggs: INTJ but consistently near the 50% mark on the I/E and T/F scales and can lean toward ENFJ depending on the environment and situation",
        "Predictive Index: Individualist",
        "Astrology: Virgo"],
    "sense of humor": [
        "sarcastic",
        "dry",
        "dark",
        "witty",
        "quick",
        "irreverent",
        "sometimes self-deprecating"],
    "personality traits": [
        "smart",
        "funny",
        "empathetic",
        "intuitive",
        "good read of body language",
        "sometimes impatient",
        "moderate workaholic",
        "constantly studying and trying to learn new skills",
        "sometimes has tendency to hyperfocus and dominate conversations"],
    "strengths": [
        "empathy",
        "intuition",
        "intelligence",
        "creativity",
        "humor",
        "ability to learn new skills quickly",
        "ability to interpret and generalize and communicate complex topics",
        "motivation to improve the world",
        "motivation to constantly learn",
        "good nutrition and general self care"],
    "weaknesses": [
        "procrastination",
        "executive function",
        "time management",
        "stress management",
        "setting boundaries",
        "indecision",
        "perfectionism",
        "overthinking",
        "overanalyzing",
        "difficulty trusting",
        "impulsivity",
        "people pleasing behaviors",
        "isolationism",
        "social anxiety"],
    "self development areas of focus": [
        "communication skills",
        "teamwork",
        "leadership",
        "cultivating healthy relationships",
        "team building",
        "time management",
        "stress management",
        "executive function",
        "setting boundaries",
        "decisiveness",
        "self confidence",
        "consistency in routine",
        "sleep hygiene",
        "self care"],
}

user_interests = {
    "programming": [
        "AI",
        "ML",
        "NLP",
        "data science",
        "data analytics",
        "app development",
        "Python",
        "neo4j",
        "SQL",
        "robotics"],
    "fitness": [
        "weightlifting",
        "rock climbing",
        "yoga",
        "myofascial release"],
    "music": [
        "heavy metal",
        "technical death metal",
        "hip-hop",
        "rap",
        "progressive metal",
        "jazz",
        "classical",
        "classic rock",
        "some electronic (but not dubstep or dumb stuff like that)",
        "folk",
        "americana",
        "acoustic guitar"],
    "environmental sustainability": [
        "renewable energy",
        "precision farming",
        "gardening",
        "permaculture",
        "land stewardship",
        "pollinator population protection",
        "sustainable agriculture",
        "sustainable building",
        "urban farming"],
    "animals": [
        "dogs",
        "cats",
        "pets",
        "wildlife",
        "nature documentaries",
        "wildlife documentaries",
        "camping",
        "fishing"],
    "cooking": [
        "professional career as a cook/chef",
        "interested in sustainable food supply chain",
        "foraging",
        "hunting",
        "fishing",
        "gardening",
        "cooking"],
    "natural sciences": [
        "biology",
        "plant life",
        "wildlife",
        "nature",
        "horticulture",
        "botany",
        "chemistry",
        "physics",
        "astronomy",
        "geology"],
}

user_influential_figures = {
    "Lex Fridman": [
        "AI",
        "ML",
        "NLP",
        "data science",
        "engineering",
        "podcasting",
        "teaching",
        "high scale platform",
        "Google",
        "MIT",
        "Tesla",
        "OpenAI",
        "DeepMind"],
    "Andrej Karpathy": [
        "AI innovation",
        "cutting edge research",
        "Tesla",
        "OpenAI"],
    "Andrew Huberman": [
        "neuroscience",
        "psychology",
        "biology",
        "physiology",
        "health",
        "wellness",
        "fitness",
        "longevity"],
    "Andrew Ng": [
        "AI",
        "ML",
        "NLP",
        "data science",
        "engineering",
        "teaching",
        "high scale platform",
        "Google",
        "Stanford",
        "deeplearning.ai"],
    "Bruce Lee": [
        "martial arts",
        "philosophy",
        "fitness",
        "health",
        "wellness",
        "longevity"],
    "Tim Ferriss": [
        "entrepreneurship",
        "business",
        "health",
        "wellness",
        "fitness",
        "longevity",
        "biohacking",
        "lifestyle design"],
    "Ryan Holiday": [
        "philosophy",
        "stoicism",
        "history",
        "writing"],
    "Daniel Pink": [
        "psychology",
        "sociology",
        "business",
        "writing"],
    "Chris Voss": [
        "negotiation",
        "psychology",
        "sociology",
        "business",
        "writing"],
    "Tony Stark": [
        "innovation",
        "inventiveness",
        "resourcefulness",
        "genius",
        "humor"],
    "Cortana": [
        "even-tempered",
        "intelligent",
        "resourceful",
        "witty"],
    "Jean-Luc Picard": [
        "wise",
        "intelligent",
        "diplomatic",
        "strong critical thinking skills",
        "strong leadership",
        "empathetic"],
    "Gandalf": [
        "wise",
        "funny",
        "strong critical thinking skills",
        "strong leadership",
        "empathetic"],
}

user_favorite_quotes = {
    "Friedrich Nietzsche": [
        "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you."
    ],
    "Albert Einstein": [
        "If at first the idea is not absurd, then there is no hope for it.",
        "We cannot solve our problems with the same thinking we used when we created them.",
        "Life is like riding a bicycle. To keep your balance you must keep moving.",
        "A person who never made a mistake never tried anything new.",
        "Look deep into nature, and then you will understand everything better.",
        "Weakness of attitude becomes weakness of character.",
        "Reality is merely an illusion, albeit a very persistent one.",
        "Imagination is everything. It is the preview of life's coming attractions.",
        "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.",
        "Logic will get you from A to B. Imagination will take you everywhere.",
        "The only reason for time is so that everything doesn't happen at once.",
        "Whoever is careless with the truth in small matters cannot be trusted with important matters.",
        "Everyone should be respected as an individual, but no one idolized.",
        "He who can no longer pause to wonder and stand rapt in awe, is as good as dead; his eyes are closed.",
        "You cannot simultaneously prevent and prepare for war.",
        "Technological progree is like an axe in the hands of a pathological criminal.",
        "Intellectuals solve problems, geniuses prevent them.",
        "Everything should be made as simple as possible, but not simpler.",
        "Great spirits have always encountered violent opposition from mediocre minds.",
        "Intellectual growth should commence at birth and cease only at death.",
        "Once we accept our limits, we go beyond them.",
        "The only source of knowledge is experience.",
        "Peace cannot be kept by force; it can only be achieved by understanding.",
        "I have no spoeical talent. I am only passionately curious.",
        "It's not that I'm so smart, it's just that I stay with problems longer.",
        "Strive not to be a success, but rather to be of value.",
        "If you can't explain it simply, you don't understand it well enough.",
    ],
    "Frank Herbert": [
        "I must not fear. Fear is the mind-killer. Fear is the little death that brings obliteration. I will face my fear and I will permit it to pass over me and through me. And when it has gone past... I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain."
    ],
    "Thomas A. Edison": [
        "I have not failed. I've just found 10,000 ways that won't work."
    ],
    "Stephen Covey": [
        "I am not a product of my circumstances. I am a product of my decisions."
    ],
    "Amelia Earhart": [
        "The most difficult thing is the decision to act, the rest is merely tenacity."
    ],
    "Babe Ruth": [
        "Every strike brings me closer to the next home run."
    ],
    "Mahatma Gandhi": [
        "Be the change that you wish to see in the world.",
        "The weak can never forgive. Forgiveness is the attribute of the strong.",
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "An eye for an eye only ends up making the whole world blind.",
        "Happiness is when what you think, what you say, and what you do are in harmony."
    ],
    "Martin Luther King Jr.": [
        "I have a dream that one day this nation will rise up and live out the true meaning of its creed: 'We hold these truths to be self-evident: that all men are created equal.'",
        "Injustice anywhere is a threat to justice everywhere.",
        "The time is always right to do what is right.",
        "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
        "Our lives begin to end the day we become silent about things that matter."
    ],
    "Mark Twain": [
        "The secret of getting ahead is getting started.",
        "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
        "If you tell the truth, you don't have to remember anything.",
        "The best way to cheer yourself up is to try to cheer somebody else up.",
        "The two most important days in your life are the day you are born and the day you find out why."
    ],
    "Oscar Wilde": [
        "Be yourself; everyone else is already taken.",
        "Always forgive your enemies; nothing annoys them so much.",
        "To live is the rarest thing in the world. Most people exist, that is all.",
        "Experience is simply the name we give our mistakes.",
        "The truth is rarely pure and never simple."
    ],
    "Winston Churchill": [
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "History will be kind to me for I intend to write it.",
        "You have enemies? Good. That means you've stood up for something, sometime in your life.",
        "Never, never, never give in except to convictions of honor and good sense.",
        "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty."
    ],
    "Warren Buffett": [
        "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.",
        "Risk comes from not knowing what you're doing.",
        "Price is what you pay. Value is what you get.",
        "Someone's sitting in the shade today because someone planted a tree a long time ago.",
        "The most important quality for an investor is temperament, not intellect."
    ],
    "Franklin D. Roosevelt": [
        "The only thing we have to fear is fear itself.",
        "Happiness lies in the joy of achievement and the thrill of creative effort.",
        "When you reach the end of your rope, tie a knot in it and hang on.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "A nation that destroys its soils destroys itself. Forests are the lungs of our land, purifying the air and giving fresh strength to our people."
    ],
    "John F. Kennedy": [
        "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
        "Those who dare to fail miserably can achieve greatly.",
        "Efforts and courage are not enough without purpose and direction.",
        "We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard."
    ],
    "Yoda": [
        "Do. Or do not. There is no try.",
        "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.",
        "Always pass on what you have learned.",
    ],
    "Obi-Wan Kenobi": [
        "In my experience there is no such thing as luck.",
        "Your eyes can deceive you. Don't trust them.",
        "The Force will be with you. Always.",
        "Who's the more foolish, the fool or the fool who follows him?",
    ],
    "Gandalf": [
        "All we have to decide is what to do with the time that is given us.",
        "I found it is the small everyday deeds of ordinary folk that keep the darkness at bay. Small acts of kindness and love.",
    ],
    "Morpheus": [
        "There is a difference between knowing the path and walking the path.",
        "I can only show you the door. You're the one that has to walk through it.",
    ],
    "Steve Jobs": [
        "Your time is limited, so don't waste it living someone else's life.",
        "Design is not just what it looks like and feels like. Design is how it works.",
    ],
}
